// regions.js - список субъектов РФ для выбора в форме
const regions = [
  { value: "moscow", name: "Москва" },
  { value: "saint-petersburg", name: "Санкт-Петербург" },
  { value: "sevastopol", name: "Севастополь" },

  { value: "adygea", name: "Республика Адыгея" },
  { value: "altai-republic", name: "Республика Алтай" },
  { value: "bashkortostan", name: "Республика Башкортостан" },
  { value: "buryatia", name: "Республика Бурятия" },
  { value: "dagestan", name: "Республика Дагестан" },
  { value: "ingushetia", name: "Республика Ингушетия" },
  { value: "kabardino-balkaria", name: "Кабардино-Балкарская Республика" },
  { value: "kalmykia", name: "Республика Калмыкия" },
  { value: "karachay-cherkessia", name: "Карачаево-Черкесская Республика" },
  { value: "karelia", name: "Республика Карелия" },
  { value: "komi", name: "Республика Коми" },
  { value: "crimea", name: "Республика Крым" },
  { value: "mari-el", name: "Республика Марий Эл" },
  { value: "mordovia", name: "Республика Мордовия" },
  { value: "sakha", name: "Республика Саха (Якутия)" },
  { value: "north-ossetia", name: "Республика Северная Осетия — Алания" },
  { value: "tatarstan", name: "Республика Татарстан" },
  { value: "tuva", name: "Республика Тыва" },
  { value: "udmurtia", name: "Удмуртская Республика" },
  { value: "khakassia", name: "Республика Хакасия" },
  { value: "chechnya", name: "Чеченская Республика" },
  { value: "chuvashia", name: "Чувашская Республика" },

  { value: "altai-krai", name: "Алтайский край" },
  { value: "zabaykalsky-krai", name: "Забайкальский край" },
  { value: "kamchatka-krai", name: "Камчатский край" },
  { value: "krasnodar-krai", name: "Краснодарский край" },
  { value: "krasnoyarsk-krai", name: "Красноярский край" },
  { value: "perm-krai", name: "Пермский край" },
  { value: "primorsky-krai", name: "Приморский край" },
  { value: "stavropol-krai", name: "Ставропольский край" },
  { value: "khabarovsk-krai", name: "Хабаровский край" },

  { value: "amur-oblast", name: "Амурская область" },
  { value: "arkhangelsk-oblast", name: "Архангельская область" },
  { value: "astrakhan-oblast", name: "Астраханская область" },
  { value: "belgorod-oblast", name: "Белгородская область" },
  { value: "bryansk-oblast", name: "Брянская область" },
  { value: "vladimir-oblast", name: "Владимирская область" },
  { value: "volgograd-oblast", name: "Волгоградская область" },
  { value: "vologda-oblast", name: "Вологодская область" },
  { value: "voronezh-oblast", name: "Воронежская область" },
  { value: "ivanovo-oblast", name: "Ивановская область" },
  { value: "irkutsk-oblast", name: "Иркутская область" },
  { value: "kaliningrad-oblast", name: "Калининградская область" },
  { value: "kaluga-oblast", name: "Калужская область" },
  { value: "kemerovo-oblast", name: "Кемеровская область — Кузбасс" },
  { value: "kirov-oblast", name: "Кировская область" },
  { value: "kostroma-oblast", name: "Костромская область" },
  { value: "kursk-oblast", name: "Курская область" },
  { value: "leningrad-oblast", name: "Ленинградская область" },
  { value: "lipetsk-oblast", name: "Липецкая область" },
  { value: "magadan-oblast", name: "Магаданская область" },
  { value: "moscow-oblast", name: "Московская область" },
  { value: "murmansk-oblast", name: "Мурманская область" },
  { value: "nizhny-novgorod-oblast", name: "Нижегородская область" },
  { value: "novgorod-oblast", name: "Новгородская область" },
  { value: "novosibirsk-oblast", name: "Новосибирская область" },
  { value: "omsk-oblast", name: "Омская область" },
  { value: "orenburg-oblast", name: "Оренбургская область" },
  { value: "oryol-oblast", name: "Орловская область" },
  { value: "penza-oblast", name: "Пензенская область" },
  { value: "pskov-oblast", name: "Псковская область" },
  { value: "rostov-oblast", name: "Ростовская область" },
  { value: "ryazan-oblast", name: "Рязанская область" },
  { value: "saratov-oblast", name: "Саратовская область" },
  { value: "sakhalin-oblast", name: "Сахалинская область" },
  { value: "sverdlovsk-oblast", name: "Свердловская область" },
  { value: "smolensk-oblast", name: "Смоленская область" },
  { value: "tambov-oblast", name: "Тамбовская область" },
  { value: "tver-oblast", name: "Тверская область" },
  { value: "tomsk-oblast", name: "Томская область" },
  { value: "tula-oblast", name: "Тульская область" },
  { value: "tyumen-oblast", name: "Тюменская область" },
  { value: "ulyanovsk-oblast", name: "Ульяновская область" },
  { value: "chelyabinsk-oblast", name: "Челябинская область" },
  { value: "yaroslavl-oblast", name: "Ярославская область" },

  { value: "khanty-mansi-ao", name: "Ханты-Мансийский автономный округ — Югра" },
  { value: "nenets-ao", name: "Ненецкий автономный округ" },
  { value: "chukotka-ao", name: "Чукотский автономный округ" },
  { value: "yamalo-nenets-ao", name: "Ямало-Ненецкий автономный округ" }
];
